//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RideBikeProjectDAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bike
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bike()
        {
            this.EventUsers = new HashSet<EventUser>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long OwnerId { get; set; }
        public long TypeId { get; set; }
        public long ProducerId { get; set; }
        public string Model { get; set; }
        public string Description { get; set; }
    
        public virtual BikeSubtype BikeSubtype { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventUser> EventUsers { get; set; }
    }
}
