//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RideBikeProjectDAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventUser
    {
        public long Id { get; set; }
        public long EventId { get; set; }
        public long UserId { get; set; }
        public Nullable<long> BikeId { get; set; }
    
        public virtual Bike Bike { get; set; }
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
